- api/src/org/labkey/api/util/ExceptionUtil.java
- core/src/org/labkey/core/admin/AdminController.java
We already do this for exception reports. This will log locally as well.
> Log threads at the time SQL deadlock exceptions to labkey.log

- experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
- experiment/src/org/labkey/experiment/api/property/DomainImpl.java
Avoid deadlock (pre-lock DomainDescriptor table)
and retry after deadlock
> 37159: Avoid deadlock (pre-lock DomainDescriptor table)

- api/src/org/labkey/api/qc/DataLoaderSettings.java
- api/src/org/labkey/api/qc/TsvDataSerializer.java
- api/src/org/labkey/api/study/assay/AbstractAssayTsvDataHandler.java
- api/src/org/labkey/api/study/assay/DefaultAssayRunCreator.java
This PR fixes Issue 36673. This fix makes it so that during assay import we convert sample names to sample IDs when you have a lookup to schema: exp.materials query: samples.
Note: For some reason the line endings setting I have configured conflicts with the repo, so it looks like I changed _entire_ files, which I did not. I am going to investigate this and hopefully push a set of changes that _do not change entire files_.
> 36673: Copy-paste tab of assay upload fails to resolve sample lookup to exp.Materials

- filecontent/webapp/File/panel/Browser.js
Accidentally stopped encoding createdBy in WebDav JSON response (#34)
Instead of reverting that change, this handles display name encoding on the client. This is consistent with how we handle encoding for all other file properties, such as name and description.
> Encode display name in file list

- core/src/org/labkey/core/webdav/list.jsp
At the top level webdav HTML view, we still display the `[ up ]` link. No nasty behavior; it just navigates away from the WebDav listing. The existing `null` check implies that this isn't expected, however.
> Don't show link to parent from WebDav root

- core/webapp/notification/Notification.css
Long display names block the notification's "Mark as read" button.
This was causing intermittent test failures on TeamCity.
Not sure why it ever passes to be honest; I was not ever able to click the button locally.
> Hide overflow of long display names

- api/src/org/labkey/api/view/template/LibClientDependency.java
- with default to "true" for libraries that do not set this property
> Revert back to using compileInProductionMode setting from lib.xml when set

- api/src/org/labkey/api/data/ConvertHelper.java
Converter interface indicates a `ConversionException` for such an error
> Throw correct exception for failed GUID conversion

- api/src/org/labkey/api/ApiModule.java
- api/src/org/labkey/api/jsp/LabKeyJspFactory.java
- api/src/org/labkey/api/jsp/LabKeyPageContext.java
- api/src/org/labkey/api/jsp/taglib/FormTag.java
We're seeing intermittent problems where FormTag.doEnd() output sometimes goes nowhere. For example, the </form> tag and csrf token might not get output on the site settings page. Attempt to fix by stashing our wrapped JspWriter and implementing popBody().
Also, register a ShutdownListener that reverts back to the default JspFactory; this prevents us from wrapping our own LabKeyJspFactory on every Tomcat reload.
> Attempt to fix issues with LabKeyJspWriter and taglibs

- study/src/org/labkey/study/view/assayProgressReport.jsp
NPE triggered by crawler: `study-reports-assayProgressReport.view?RowId=<injection string>`
```
java.lang.NullPointerException
at org.labkey.jsp.compiled.org.labkey.study.view.assayProgressReport_jsp._jspService(assayProgressReport_jsp.java:177)
at org.labkey.api.view.JspView.renderView(JspView.java:170)
at org.labkey.api.view.WebPartView.renderInternal(WebPartView.java:371)
```
> Prevent NPE from bad reportId

- api/src/org/labkey/api/view/ViewServlet.java
The link crawler is triggering this error.
> Change log level for misuse of `.lastFilter` parameter

- api/build.gradle
This change will cause no harm with the current gradlePlugin release, but requires gradlePlugins > 1.4.4, which has a fix for the PomFile task, in order for the pom file to include the labkey dependency with the proper classifier for the schemas jar.
> Issue 37308: add xmlSchemas jar as api dependency so it will be included in pom file

- study/test/src/org/labkey/test/tests/study/StudyExportTest.java
The `.toggle` checkbox behaves unusually when data region rows are disabled
> Use helper to select all rows in data region

- api/src/org/labkey/api/data/CompareType.java
- api/src/org/labkey/api/data/SimpleFilter.java
Issue 37524: QueryWebPart with CONTAINS filter and value that includes an underscore will generate incorrect filter on the "select all" url
> 37524: use unescaped value on URL for CONTAINS

- api/src/org/labkey/api/data/dialect/SqlDialect.java
- api/src/org/labkey/api/data/dialect/sqlKeywords.txt
- bigiron/src/org/labkey/bigiron/mysql/MySql80Dialect.java
- core/src/org/labkey/core/dialect/PostgreSqlDialectFactory.java
- core/src/org/labkey/core/dialect/PostgreSql_12_Dialect.java
Add PostgreSQL 12 dialect, adjust dialect retrieval tests.
Recommend PostreSQL 11.x.
Adjust MySQL reserved word list to match recent changes. Fix messages.
> Support PostgreSQL 12 (currently in beta)

- api/src/org/labkey/api/exp/query/ExpSchema.java
I must have intended to delete the original check in a refactor. The two different approaches route through the same code and produce identical results.
> Issue 37564: Duplicate conditions in ExpSchema.java

- core/src/org/labkey/core/admin/AdminController.java
Note: Gear button that links to this page appears on the Navigation drop-down button.
> Fix crawler failure: re-allow manage folders action in root

- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- experiment/src/org/labkey/experiment/deriveSamplesChooseTarget.jsp
- merge session selection instead of just the current page selection
- clear selection after operation completes successfully
- default the target sample set when deriving samples to the current sample set
> Issue 37522: Sample Derive button only selects first page of samples

- api/src/org/labkey/api/query/QueryForm.java
Let other, existing error handling catch the fact that we're missing "query.queryName" and "query"
> Fix ExternalSchemaTest - don't special case-check for "queryName" parameter

- api/src/org/labkey/api/study/assay/DefaultAssayRunCreator.java
- fix logic error in addMaterialById to include materials not in a sample set
> Issue 37574: run lookup to exp.Materials not attached as input to run

- query/src/org/labkey/query/sql/QueryTable.java
> Issue 32048: Query$QueryInternalException caused by NPE

- study/src/org/labkey/study/assay/AssayServiceImpl.java
- study/src/org/labkey/study/controllers/assay/actions/GetProtocolAction.java
Updated getAssayDefinition to return null if AssayProvider not found.  Throw NotFoundException in GetProtocolAction if getAssayDefinition returns null.
> Issue 36980: Assay getProtocol getting NPE if assay definition not found

- api/src/org/labkey/api/query/QueryForm.java
- api/src/org/labkey/api/query/UserSchemaAction.java
- api/src/org/labkey/api/query/snapshot/AbstractSnapshotProvider.java
- api/src/org/labkey/api/study/actions/PublishConfirmAction.java
- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- query/src/org/labkey/query/controllers/QueryController.java
- query/src/org/labkey/query/controllers/TableInfoForm.java
- query/src/org/labkey/query/controllers/ViewQuerySourceAction.java
Now propagating containerFilter setting into QuerySettings before the QueryView creates the TableInfo, which must knows its ContainerFilter instance at construction time
Also, make QueryForm.getQueryDef() throw NotFoundException instead of return null. This simplifies many callers, and prevents NPEs
> Fix problem where container filter wasn't getting applied in SelectRows, and NPEs around QueryForm.getQueryDef()

- api/src/org/labkey/api/data/MaterializedQueryHelper.java
- api/src/org/labkey/api/data/dialect/MutatingSqlDetector.java
- api/src/org/labkey/api/data/dialect/StatementWrapper.java
Stop flagging creation of temp table indexes as "mutating"
Remove old mutating SQL detection approach
Pass through and log SQL along with unrecognized keyword message
> Recognize a couple more keywords ("ANALYZE", "{call")

- core/src/org/labkey/core/webdav/DavController.java
Not safe to subtract longs and cast to an int.
> Issue 37730: File listing doesn't sort properly with files larger than 2GB

- api/src/org/labkey/api/data/AbstractTableInfo.java
- api/src/org/labkey/api/query/QueryView.java
- list/src/org/labkey/list/model/ListDefinitionImpl.java
- query/src/org/labkey/query/controllers/QueryController.java
Change default Excel template to be XLSX instead of XLS, but add parameter to let client choose
Make list import UI go through codepath that applies XML metadata, allowing override of template URL
> Issue 37217: Update download template to xlsx and provide metadata options

- api/gwtsrc/org/labkey/api/gwt/client/LockedPropertyType.java
- api/gwtsrc/org/labkey/api/gwt/client/model/GWTPropertyDescriptor.java
- internal/src/org/labkey/api/exp/property/DomainUtil.java
To avoid serialization issues on teamcity postgres.
> Changed variable type LockPropertyType to StringProperty in GWTPropertyDescriptor

- experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
- experiment/src/org/labkey/experiment/api/ExpSampleSetTestCase.java
- experiment/src/org/labkey/experiment/api/ExpTableImpl.java
include "Alias" on exp.Materials and sample set tables
> Issue 36979: Restore the Alias column on SampleSet

- api/src/org/labkey/api/data/queryprofiler/QueryProfiler.java
Useful when you're working with very long queries
> Convenience link to copy text of query to clipboard with single click

- wiki/resources/web/wiki/internal/wikiEdit.js
- wiki/src/org/labkey/wiki/view/wikiEdit.jsp
File attachments now use conventional file picker rather than unstandardized code unique to wiki edit page.
> Issue 30769: Migrate wiki edit page to use standard JS file chooser

- announcements/webapp/announcements/discuss.js
Updated regrexes for Wiki and Markdown detection.
> Issue 36577: Messages warns about Markdown formatting likely being Wiki formatting

- api/src/org/labkey/api/data/NameGenerator.java
- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- case-insensitive check for MaterialInputs parent column name
- don't bother joining by ',' just to split it apart again later
> Issue 37268: experiment-derive.api doesn't include parents in name expression

- api/src/org/labkey/api/data/DataRegion.java
- api/webapp/clientapi/dom/DataRegion.js
- query/src/org/labkey/query/LinkedSchema.java
- query/src/org/labkey/query/LinkedTableInfo.java
Also, prompt for parameters on linked schema queries that include them
New QueryWebPart option to suppress filters and parameter values in the header
> Issue 37826: Lookup from linked schema query to a non-linked schema target fails to apply proper ContainerFilter

- api/src/org/labkey/api/util/FileUtil.java
- experiment/src/org/labkey/experiment/api/ExpDataImpl.java
- experiment/src/org/labkey/experiment/api/ExpDataTableImpl.java
Also, left-align URLs in UI (defaulted to right-aligned since the column wraps RowId, an integer)
> Issue 37861: ExpData.getWebDavURL returns double encoded path in S3 folders

- announcements/src/org/labkey/announcements/AnnouncementsController.java
'Admin' dropdown option now only available in Page Admin Mode.
'Email' sub-menu option now only available in Page Admin Mode. When not in Page Admin Mode, only 'Email Preferences' is available.
> Issue 33909: Suppress some Messages menu content when not in Page Admin Mode

- api/src/org/labkey/api/dataiterator/SimpleTranslator.java
- experiment/src/org/labkey/experiment/ExpDataIterators.java
- experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
Corrected column type to prevent error when an attempting to import an alias column
> Issue 37946: Alias column conflict with import alias

- api/gwtsrc/org/labkey/api/gwt/client/ui/property/FormatItem.java
- api/src/org/labkey/api/util/HelpTopic.java
- api/src/org/labkey/api/util/PageFlowUtil.java
Make JDK JavaDoc base URL available to client code via LABKEY.jdkJavaDocLinkPrefix
Dependency for https://github.com/LabKey/glass-components/pull/35
Simple example:
```javascript
<script type="text/javascript">
document.write('<a href="' + LABKEY.jdkJavaDocLinkPrefix + 'java/text/DecimalFormat.html"/>My Page</a>');
</script>
```
> Item 5864: Type-Dependent Layout (Domain Designer)

- api/src/org/labkey/api/data/bigiron/ClrAssemblyManager.java
Should fix an error that happened during server startup on a TeamCity run:
```
ERROR WebPartView              2019-07-12 02:14:22,117     http-nio-8111-exec-2 : renderView() exception in org.labkey.api.view.JspView while responding to /labkey/admin-moduleStatus.view?returnUrl=%2Flabkey%2FHome%2Fproject-begin.view%3F
java.util.ConcurrentModificationException
at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
at org.labkey.api.data.bigiron.ClrAssemblyManager.addAdminWarningMessages(ClrAssemblyManager.java:48)
at org.labkey.bigiron.mssql.BaseMicrosoftSqlServerDialect.addAdminWarningMessages(BaseMicrosoftSqlServerDialect.java:1653)
at …
```
> Prevent ConcurrentModificationException in ClrAssemblyManager

- api/src/org/labkey/api/exp/api/ExperimentService.java
- api/src/org/labkey/api/exp/api/ExperimentUrls.java
- core/src/org/labkey/core/query/UsersDomainKind.java
- experiment/src/client/DomainDesigner/DomainDesigner.tsx
- experiment/src/org/labkey/experiment/ExperimentModule.java
- experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
- experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- internal/src/org/labkey/api/query/SimpleTableDomainKind.java
- internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
- study/src/org/labkey/study/controllers/StudyDefinitionController.java
- study/src/org/labkey/study/query/studydesign/AbstractStudyDesignDomainKind.java
Currently supported for the following domains: site users props, study add. props, extensible tables, sample sets, data classes
> UX Domain Designer experimental feature flag

- api/src/org/labkey/api/files/FileContentService.java
- api/src/org/labkey/api/files/view/CustomizeFilesWebPartView.java
- api/src/org/labkey/api/pipeline/PipeRoot.java
- api/src/org/labkey/api/pipeline/view/SetupForm.java
- filecontent/src/org/labkey/filecontent/FileContentServiceImpl.java
- pipeline/src/org/labkey/pipeline/PipelineController.java
- pipeline/src/org/labkey/pipeline/api/PipeRootImpl.java
- pipeline/src/org/labkey/pipeline/api/PipelineServiceImpl.java
Creating new FB and PR against the 19.2 branch
> Issue 37866: NPE in ExperimentController$ShowFileAction.getDataView()

- .gitattributes
- api/src/org/labkey/api/data/BeanObjectFactory.java
- api/src/org/labkey/api/security/roles/Role.java
- api/src/org/labkey/api/security/roles/RoleManager.java
- api/src/org/labkey/api/util/GUID.java
- api/src/org/labkey/api/view/Portal.java
- assay/src/org/labkey/assay/security/AssayDesignerRole.java
This allows us to rename and repackage roles and permissions but still resolve the old names that may be serialized in the database or folder archives.
Add "org.labkey.study.security.roles.AssayDesignerRole" as an alias for org.labkey.assay.security.AssayDesignerRole to fix QC Trend Report tests. These tests import a folder archive (QC Trend Report Testing.folder.zip) that includes role assignments with the old role name.
> Add "serialization aliases" mechanism to Role

- api/src/org/labkey/api/data/BeanObjectFactory.java
- api/src/org/labkey/api/security/roles/Role.java
- api/src/org/labkey/api/security/roles/RoleManager.java
- api/src/org/labkey/api/security/roles/SeeUserAndGroupDetailsRole.java
- assay/src/org/labkey/assay/security/AssayDesignerRole.java
- core/src/org/labkey/core/query/CoreQuerySchema.java
- core/src/org/labkey/core/query/UsersTable.java
Reflect expanded purpose of role. Use getSerializationAliases() to maintain backward compatibility with previous name.
> Rename SeeUserDetailsRole -> SeeUserAndGroupDetailsRole

- api/src/org/labkey/api/data/ContainerFilter.java
- experiment/src/org/labkey/experiment/ParentChildView.java
- experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
- Issue 37982: Sample Set: Link to precursor sample set does not resolve correctly if sample has parents in current sample set and a sample set in the parent container
- Issue 38018: Sample Set: Multiple data inputs from different containers are not shown in the Parent Data grid
> Sample details container filtering issues

- api/src/org/labkey/api/study/actions/UploadWizardAction.java
create batch and run tables via the assay's protocol schema so metadata xml is applied
> Issue 37043: Filtered lookup with assay run upload form

- api/src/org/labkey/api/assay/AssayProtocolSchema.java
Revert ill-advised attempt to remove study dependency. Should fix "Target Study" column issues in ElispotAssay, Viability, TargetStudy tests.
> Item 5015: Assay without Study

- query/src/org/labkey/query/controllers/QueryController.java
`_print` variable needs to be set to true so `isPrint()` function in `super.getView()` works as expected.
> Issue 38218: Print preview bugfix into 19.2

- wiki/resources/web/wiki/internal/wikiEdit.js
Moved much of wikiEdit.js's own isDirty checking to labkey.js's isDirty functions.
Note that dirty state of the body field has to be handled separately. I tried to implement a nicer jQuery way to detect keystrokes, but they didn't work. I'm assuming this is why the original author had to use the tinyMCE detection methods in the first place.
(Also, the deleted line '$(_idSel + 'body').keypress(setWikiDirty).change(setWikiDirty);' that was ostensibly setting body dirtiness with jQuery was actually not doing anything functional at all.)
I waffled as to whether to modularize calls to LABKEY.setDirty(false) and then setBodyClean() into their own function. Doing it would be /slightly/ more modular, but also introduce another non-labkey.js dirtiness handling function.
> Issue 30769: Consolidate dirty handling

- api/src/org/labkey/api/data/ResultSetImpl.java
- experiment/src/org/labkey/experiment/api/SampleSetUpdateServiceDI.java
- experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
- GenerateNamesDataIterator to call super.close() to clean up properly
- Run onSamplesChanged callback as a POSTCOMMIT task
> Issue 38209: leaked ResultSetImpl created by SampleSetUpdateServiceDI

- api/src/org/labkey/api/jsp/LabKeyJspWriter.java
`Boolean` should be safe to render without escaping
> Remove unnecessary JSP print warning

- core/src/org/labkey/core/admin/customizeEmail.jsp
The JSON property names we used to set and get the values got out of sync.
> Issue 38299: Email template UI doesn't show HTML/plain text separator help

- api/src/org/labkey/api/resource/AbstractResource.java
Followup from Issue 38376: Multi-file download from root of S3 backed files web part cannot be unzipped on Windows
> Disallow empty path name elements in WebDav resources

- search/src/org/labkey/search/model/tikaConfig.xml
Excluding HDF parser from tika
> Issue 38386: Tika cant find parser class for HDF files

- api/src/org/labkey/api/search/SearchService.java
- core/src/org/labkey/core/search/NoopSearchService.java
- search/src/org/labkey/search/SearchController.java
- search/src/org/labkey/search/SearchModule.java
- search/src/org/labkey/search/model/LuceneSearchServiceImpl.java
- search/src/org/labkey/search/view/search.jsp
- study/test/src/org/labkey/test/tests/search/SearchTest.java
This allows sorting of search results by container, and allows search order to be inverted.  It also adds a test for this and expands coverage on the existing search UI
> Allow sort of search results by container

- api/src/org/labkey/api/data/Container.java
In Container.getActiveModules(), it attempts to look at available assays and automatically add the modules they declare as active. That's great, but if the assay declares a dependency on module1, and this module depends on module2, that's not added. If we only turn on Module1 but not module2, we can get errors. One could argue that's the developer's mistake; however, it seems like we could do a check here and avoid it. there's no way for the user to go to the UI and turn on module1 w/o module2 automatically being added, so I'd argue we ought to do the same thing here.
> When adding assay modules, also include dependencies

- study/src/org/labkey/study/CohortFilterFactory.java
The link crawler was throwing garbage parameters at a study portal:
```
/SharedStudyTest%20Project/study-overview.view?AnalyteTitration.containerFilterName=--%3E%22%3E%27%3E%27%22%3C%2Fscript%3E%3Cimg+src%3D%22xss%22+onerror%3D%22alert%28%228%28%22%29%3E&providerName=TZM-bl+Neutralization+%28NAb%29&viewName=&uploadAttemptID=e2179df3-b7f4-1037-bf66-6028cdc9d1e6&maximumErrorRate=&Key+%26%25%3C%2B=1&identifier=&labTransformVersion=&scriptId=586&groups%5B2%5D=-3
```
and triggered this 500 response:
```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error
at index 0 in: "<+"
at java.base/java.net.URLDecoder.decode(URLDecoder.java:232)
at java.base/java.net.URLDecoder.decode(URLDecoder.java:142)
at …
```
> CohortFilterFactory shouldn't choke on bad URL parameters

- api/webapp/clientapi/dom/DataRegion.js
- api/webapp/clientapi/ext3/FilterDialog.js
This new behavior is causing numerous test failures. I'd like to revert it temporarily to make the tests happy while we work out a solution.
> Don't remove selection when changing DataRegion filters

- api/src/org/labkey/api/jsp/taglib/ButtonTag.java
- api/src/org/labkey/api/jsp/taglib/LinkTag.java
- assay/src/org/labkey/assay/view/updateQCState.jsp
- query/src/org/labkey/query/view/internalNewView.jsp
- study/src/org/labkey/study/assay/view/publishChooseStudy.jsp
Slim down LinkTag and ButtonTag - remove unused (and NYI) setters plus corresponding handling
Remove double encoding (ButtonTag.setHref())
> Migrate more attributes() usages to new simple setters

- core/src/org/labkey/core/CoreController.java
Alias DismissWarningsAction to DismissCoreWarningsAction to appease @glass
Correct CDS to use the new dismissal action name
> Fix Biologics' and CDS' ability to close warning banners

- api/src/org/labkey/api/data/DbScope.java
Fix TempTableInClauseGenerator tests which are relying on ordering to make sure the right cached version of the temp table is being used
> Retain order of commit tasks when we invoke them

- api/src/org/labkey/api/util/DateUtil.java
- parse fractional seconds as milliseconds
- move fix for Issue 36691 into DateUtil: trim millis to 3 decimal places
> Issue 38649: flow: parse fractional seconds used in $BTIM keyword

- api/src/org/labkey/api/query/UserIdRenderer.java
- api/src/org/labkey/api/security/SecurityManager.java
- api/src/org/labkey/api/security/UserManager.java
Deleted user has an ID of 3218. Pictures below show examples of how we would be using the ID.
Link is removed if there is no user or the user doesn't have access to see the link.
When a user doesn't have permissions to see another user's details page (assigned to column):
> Issue 38694: Links to deleted users cause NPEs and other problems fix

- pipeline/src/org/labkey/pipeline/api/PipelineJobServiceImpl.java
I think this commit (https://github.com/LabKey/testAutomation/commit/6c9fb4befdfd53c4ca5d159f6b91b3692352a477#diff-ff11edf87ffbf4025704442af895726d) caused the pipeline to get cached differently.
> Update integration test to account for change to pipelinetest module

- pipeline/src/org/labkey/pipeline/api/PipelineJobServiceImpl.java
The way we pass `JAVA_HOME` to Tomcat has changed slightly in the latest gradle plugin, causing this test to fail on TeamCity Windows agents.
Tomcat starts just fine with mixed `/` and `\` in `JAVA_HOME` so the test should be fine with either.
> Match file separators in test

- core/src/org/labkey/core/user/UserController.java
`UnauthorizedException` doesn't really make sense because nobody can view or edit details for the guest user; it isn't a matter of insufficient permission
> More appropriate response for attempting to view/edit guest user details

- api/src/org/labkey/api/exp/api/ExpProtocolAttachmentType.java
Changing SQL to match `ExpRunAttachmentType`
https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=38885
> 38885: ExpProtocolAttachmentType breaks attachment query on SQL Server

- experiment/src/org/labkey/experiment/api/ExperimentRunGraphForLookup2.jsp
- add cast for string literals for postgres 9.5.19
> Issue 38887: lineage query broken on pg 9.5.19

- core/src/org/labkey/core/user/UserController.java
- bring back ShowUpdateAction bulk validation of columns to show all column errors at once on LKS user profile submit
- change testSiteUsersPermission check to expect the Last Login field to be present, even for a non-site admin
> UserTest fixes for user profile changes

- api/src/org/labkey/api/data/DataColumn.java
- experiment/src/org/labkey/experiment/api/ExpRunTableImpl.java
- When the lookup column is not the PK column, don't attempt to
convert the new and old values for the audit log message.
- On update form reshow, use the submitted form value instead of
the stringified id value.
> Issue 38504: Update Run properties fails to resolve string lookups

- query/src/org/labkey/query/sql/QuerySelect.java
- query/src/org/labkey/query/sql/QueryUnion.java
there is more opportunity for optimization (e.g. recognize when inner ORDER BY is a no-op)
> Issue 38988: Simple LabKey SQL query on SQL Server results in ORDER BY error

- internal/src/org/labkey/api/exp/property/DomainUtil.java
PropertyDescriptor's rangeURI could be stored as a simple type name (e.g. "int") instead of a full property type URI.
Use the resolved PropertyType's typeURI if possible, otherwise the stored rangeURI.
> Restore serialized GWTProperty.rangeURI behavior

- api/src/org/labkey/api/ApiModule.java
- api/src/org/labkey/api/data/CompareType.java
- api/src/org/labkey/api/data/ConditionalFormat.java
- api/src/org/labkey/api/data/DataColumn.java
- api/src/org/labkey/api/data/DataRegion.java
- api/src/org/labkey/api/data/ExcelColumn.java
- api/src/org/labkey/api/data/SimpleFilter.java
- api/src/org/labkey/api/security/SecurityPolicy.java
- experiment/src/org/labkey/experiment/api/ExpRunTableImpl.java
- experiment/src/org/labkey/experiment/api/VocabularyDomainKind.java
- experiment/src/org/labkey/experiment/api/data/ChildOfCompareType.java
- experiment/src/org/labkey/experiment/api/data/ParentOfCompareType.java
- internal/src/org/labkey/api/exp/property/DomainUtil.java
- internal/src/org/labkey/api/query/ExtendedTableDomainKind.java
- validate conditional formats when saving domain and before rendering DataRegion
- support '~me~' in conditional filter value for user columns
- support relative date parsing of conditional format filter value
- use date parsing when matching BETWEEN filter of a conditional format of a date column
e.g, to highlight dates for today use a conditional format like query.dateColumn~between=-0d,+0d
> Issue 39223: conditional format filters don't support ~me~ value replacement

- api/src/org/labkey/api/assay/AbstractAssayTsvDataHandler.java
- api/src/org/labkey/api/data/ConditionalFormat.java
- create a default object value of the right type when validating the format
- fixes ClassCastException in CompareType.GTE.meetsCriteria
> Use correct type in ConditionalFormat.validateFormat

- survey/src/org/labkey/survey/SurveyController.java
Issue 39291: Survey UI not loading when editing previously saved survey, tied to date based dataset
> 39291: Can't assume the survey response PK never changes

- query/webapp/query/browser/view/QueryDetails.js
Add a small placeholder component to the query details tab and replace with the dependency report once the query analysis returns.
> 39247 : Don't block the entire schema browser while waiting for query dependencies

- announcements/src/org/labkey/announcements/model/AnnouncementManager.java
Tested this on a 19.3 enlistment with dumbster, confirmed that usernames with special characters are no longer double-encoded, and now display properly.
> Issue 39090: Escape usernames in email notifications.

- api/webapp/clientapi/dom/WebSocket.js
- fix is to be more targeted in what event code/reason we use for "server shutdown"
- this is causing multiple test failures on TeamCity
> WebSocket fix for issue with Firefox sending unexpected event code on page reload

- study/test/src/org/labkey/test/tests/study/StudyVisitManagementTest.java
Targeting develop since it's test bug instead of app bug. Let me know if that needs to be changed.
StudyVisitManagementTest.testFailForUndefinedVisitsReload started to fail after lastModified for uploaded file has been corrected to actual file's modified timestamp, instead of upload timestamp. 
This test has been relying on upload timestamp as file's last modified, hence it started to fail. 
Change made to update file's modified prior to upload. 
https://teamcity.labkey.org/project.html?projectId=LabkeyTrunk&testNameId=8683724906803122396&tab=testDetails
> Fix test with lastModified date fix for webDav

- api/webapp/clientapi/core/Security.js
- assay/package-lock.json
- assay/package.json
- core/src/org/labkey/core/CoreModule.java
- core/src/org/labkey/core/login/LoginController.java
- core/src/org/labkey/core/login/PasswordRule.java
- core/src/org/labkey/core/login/setPassword.jsp
- core/src/org/labkey/core/security/SecurityApiActions.java
- experiment/package-lock.json
- experiment/package.json
- add SiteSettings.homeProjectResetPermissions startup property to reset/remove guest access from home project SecurityPolicy
- allow optionalMessage param for CreateNewUserAction (this was already supported in the new user email template)
- add optionalMessage param to the LABKEY.Security.createNewUser config object
> Item 6571: Change to support Sample Manager new user email content and hosted server setup
