LabKey/platform

- api/src/org/labkey/api/exp/ObjectProperty.java
- api/src/org/labkey/api/study/assay/AbstractAssayTsvDataHandler.java
- trim assay data to null during import
[TC](https://teamcity.labkey.org/viewType.html?buildTypeId=bt8&branch_LabkeyTrunk=assay_trim_null_36368&tab=buildTypeStatusDiv)
> 36368: Boolean column for assay with whitespace results in false

- api/webapp/clientapi/core/Filter.js
- api/webapp/clientapi/core/Query.js
- internal/webapp/internal/ViewDesigner/field/FilterTextValue.js
- internal/webapp/internal/ViewDesigner/tab/FilterTab.js
- parse the filter value during validateMultiple
- turn the filter value into a string when rendering the customize view filter input field
> Issue 37116: Multi-value foreign key filter broken in customize view

- core/src/org/labkey/core/junit/JunitController.java
- core/src/org/labkey/core/junit/JunitManager.java
Wrapping up work on this branch, pulling back into the original branch.
> Fb performance metrics

- api/src/org/labkey/api/module/ModuleLoader.java
Pushing for Ankur: Updated source path for project root in ModuleLoader to coincide with new api location
> Update ModuleLoader to use correct source path

- api/webapp/clientapi/core/Utils.js
- api/webapp/clientapi/dom/Query.js
- api/webapp/clientapi/dom/Utils.js
- consolidate three hidden form util methods into one
- move utility methods touching DOM into dom/Utils.js
> move postToAction into dom/Utils.js

- core/src/org/labkey/core/junit/JunitController.java
Added extra timer output to the junit result page. Will now show total time, min, max, average and number of times a timer (test) was called.
> Adding more timer output data and a titles.

- core/webapp/editInPlaceElement.js
Received this patch from Ben Bimber. Related changes in SVN (r63237)
> Fix encoding for editInPlaceElement

- .gitignore
- api/gwtsrc/org/labkey/api/gwt/client/assay/model/GWTPropertyDescriptorMixin.java
- api/webapp/clientapi/core/Domain.js
- experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
Add domainId to Domain.get and Domain.save.  Needed for new domain designer UI.
> [LabKey UX] Edit standard settings name/label/type - Domain API updates

- announcements/src/org/labkey/announcements/AnnouncementsController.java
- api/src/org/labkey/api/data/BeanObjectFactory.java
- api/src/org/labkey/api/data/TableViewForm.java
- api/src/org/labkey/api/study/actions/AssayRunUploadForm.java
- api/src/org/labkey/api/view/WebPartView.java
ERROR ExceptionUtil            2019-04-16 05:26:29,446     http-nio-8111-exec-2 : Unhandled exception: 500: Unexpected server error
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.labkey.api.data.TableViewForm.setPkVals(TableViewForm.java:328)
at org.labkey.api.data.TableViewForm.setPkVals(TableViewForm.java:321)
at org.labkey.api.data.TableViewForm.setViewContext(TableViewForm.java:759)
at org.labkey.api.query.QueryUpdateForm.<init>(QueryUpdateForm.java:48)
at org.labkey.api.query.UserSchemaAction.bindParameters(UserSchemaAction.java:74)
at org.labkey.query.controllers.QueryController$InsertQueryRowAction.bindParameters(QueryController.java:2471)
> Fix some crawler errors from bad URL parameters

- api/src/org/labkey/api/query/ExportScriptModel.java
- api/src/org/labkey/api/query/JavaScriptExportScriptModel.java
- api/src/org/labkey/api/query/PerlExportScriptModel.java
- api/src/org/labkey/api/query/RExportScriptModel.java
@labkey-jeckels - this is related to: Ticket 37190.  It adds colSelect to the export vignette for R scripts, and consolidates some code.
> Ticket 37190: Show columns in the R export vignette?

- api/src/org/labkey/api/data/Parameter.java
Try this again, hopefully with better line endings
> Issue 36954: Attempting to continue after a trigger script error but the connection is in a bad state

- internal/webapp/internal/ZipLoad/ZipLoad.js
Hi Cory,
Can you please code review this change for this issue ?
https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=37392
Thanks,
Ankur
> Issue37392: JS error when attempting to drag-drop upload a file

- api/src/org/labkey/api/data/Table.java
Should help with IDRI formulations test
> Log more details for alias checking case

- api/src/org/labkey/api/query/FilteredTable.java
- internal/src/org/labkey/api/query/SimpleUserSchema.java
- query/src/org/labkey/query/ExternalSchema.java
- query/src/org/labkey/query/data/ExternalSchemaTable.java
- study/src/org/labkey/study/query/DatasetTableImpl.java
Remove deprecated and unused SimpleTable constructor
> Fix external schema tables to never pass through container filters

- api/src/org/labkey/api/security/AuthenticationManager.java
Log to both labkey.log and audit log
Also fix loathsome bogosity in enum usage
> Issue #37464: Append IP address to end of all login failure messages

- api/src/org/labkey/api/files/TableUpdaterFileListener.java
Removed code you suggested plus another few lines elsewhere.
> Issue 36849: Simplify URI handling in TableUpdaterFileListener

- api/src/org/labkey/api/data/ContainerManager.java
- api/src/org/labkey/api/data/DbSequence.java
- api/src/org/labkey/api/data/DbSequenceManager.java
- api/src/org/labkey/api/data/NameGenerator.java
- api/src/org/labkey/api/dataiterator/SimpleTranslator.java
- api/src/org/labkey/api/exceptions/OptimisticConflictException.java
- api/src/org/labkey/api/exp/api/ExperimentService.java
- api/src/org/labkey/api/exp/api/SampleSetService.java
- api/src/org/labkey/api/util/SubstitutionFormat.java
- experiment/src/org/labkey/experiment/ExpDataIterators.java
- experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
- list/src/org/labkey/list/model/ListManager.java
- study/src/org/labkey/study/importer/SpecimenImporter.java
core.DbSequences.Value is BIGINT, make API match
> DbSequenceManager int->long

- api/src/org/labkey/api/security/AuthenticatedRequest.java
- api/src/org/labkey/api/util/PageFlowUtil.java
Tried in vain to repro with a custom build of tomcat 8.5.32.  Still can't hurt to add these two user-agents to isRobot().
> Fb 35905 needs a session

- core/src/org/labkey/core/admin/AdminController.java
Form field is null. Should not be in most cases, but good to check.
> Issue 37024: NPE with MigrateFilesOption

- query/src/org/labkey/query/sql/QueryPivot.java
Don't cache alias name with rest of pivot sql
> issue 37633

- api/src/org/labkey/api/data/Aggregate.java
- api/src/org/labkey/api/data/TableSelector.java
Problem was that SQLFragments were string-ized and then combined with more SQLFragments, which doesn't allow SQLFragment to handle WITH as it knows how.
Goes with premium change.
> Issue 32506: Summary Statistics against query with WITH throws exception

- api/src/org/labkey/api/exp/XarContext.java
- api/src/org/labkey/api/exp/XarSource.java
- experiment/src/org/labkey/experiment/XarReader.java
- experiment/src/org/labkey/experiment/api/ExpMaterialImpl.java
- experiment/src/org/labkey/experiment/xar/AbstractXarImporter.java
> Issue 34653: Constraint violation in XAR import due to material LSID/name mismatch

- api/src/org/labkey/api/data/DataRegion.java
- api/src/org/labkey/api/exp/XarContext.java
- api/src/org/labkey/api/exp/XarSource.java
- api/src/org/labkey/api/exp/api/ProtocolImplementation.java
- api/src/org/labkey/api/query/QueryForm.java
- api/src/org/labkey/api/query/UserSchema.java
- api/src/org/labkey/api/study/assay/AssayProtocolSchema.java
- api/src/org/labkey/api/util/ExceptionUtil.java
- core/package-lock.json
- core/package.json
- experiment/package-lock.json
- experiment/package.json
- experiment/src/org/labkey/experiment/XarReader.java
- experiment/src/org/labkey/experiment/api/ExpMaterialImpl.java
- experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
- experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
- experiment/src/org/labkey/experiment/api/SampleSetUpdateServiceDI.java
- experiment/src/org/labkey/experiment/xar/AbstractXarImporter.java
- pipeline/src/org/labkey/pipeline/status/PipelineQueryView.java
- query/src/org/labkey/query/controllers/QueryController.java
- study/src/org/labkey/study/query/PublishedRecordQueryView.java
Issue 37604: link flow samples to fcs files on sample import
- call SampleSet.onSamplesUpdated to notify FlowProtocolImplementation
> Issue 37604: link flow samples to fcs files on sample import

- experiment/src/org/labkey/experiment/api/ExpSampleSetTestCase.java
- experiment/src/org/labkey/experiment/api/LineageForeignKey.java
- avoid hardcoded 'lsid' in LineageForeignKey
- regression test
> Issue 37690: bad sql generated for lookup to Sample with lineage lookup

- api/src/org/labkey/api/query/QueryForm.java
- api/src/org/labkey/api/query/QueryView.java
Hopefully this is the end of the chain...
> Fix NPE when deleting query view, and resume show query parse errors in executeQuery

- experiment/resources/schemas/dbscripts/postgresql/exp-19.11-19.12.sql
- experiment/resources/schemas/dbscripts/sqlserver/exp-19.11-19.12.sql
- experiment/resources/schemas/exp.xml
- experiment/src/org/labkey/experiment/ExperimentModule.java
- experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
- experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
- experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=37592
> Issue 37592: Add search document for SampleSets

- study/src/org/labkey/study/view/specimen/importSpecimens.jsp
fix AliquotTest
- use raw string in labkey:radio currentValue so Objects.equals in RadioTag.isChecked will return true
- add expected error message to test
fix SampleSetTest
- expected audit log message has changed
> fix AliquotTest and SampleSetTest

- api/src/org/labkey/api/exp/api/ExperimentService.java
- experiment/src/org/labkey/experiment/ParentChildView.java
- experiment/src/org/labkey/experiment/api/ExpMaterialImpl.java
- experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- adjusted queries for deleting runs based on sample deletion
> Issue 37582: Deleting sample deletes derivation run as well, removing lineage from “sister” samples

- api/src/org/labkey/api/query/QueryService.java
- query/src/org/labkey/query/QueryServiceImpl.java
- query/src/org/labkey/query/sql/Method.java
- add ability to register a query method
- don't traverse QDot expression tree to find additional FieldKeys when creating where clause; you are the FieldKey
> Issue 37670: Filter assay results by sample lookups on run OR results

- api/build.gradle
- internal/build.gradle
Update dependency declarations
> Item 5613: Remove Server Builds dependency on local Tomcat install

- api/src/org/labkey/api/study/assay/AssayProtocolSchema.java
- study/test/src/org/labkey/test/tests/study/AssayQCTest.java
This is mostly adding tests.
When merging, also ensure that testAutomation/fb_assayQCTestFixes is merged
> Fb assay qc testing

- query/src/org/labkey/query/sql/QAggregate.java
@labkey-kevink Creating with 19.2 as the target. Can you review?
> Issue 37869: Propagate column metadata for additional SQL aggregates

- api/src/org/labkey/api/action/QueryViewAction.java
Should help with other QueryViewAction uses
> Issue 37914: Select All from genotyping runs grid only selects first page of data

- experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
- rethrow RemapPostConvert's ConversionException as ValidationException
> Issue 37891: failing to resolve sample parent throws ConversionException

- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- experiment/src/org/labkey/experiment/createSampleSet.jsp
Fix flow tests broken by previous changes.
> Issue 37219: Sample set Parent column

- core/module.properties
Missed the core module version bump (?!)
> 5869: Consolidate 19.2 release scripts

- experiment/package-lock.json
- experiment/package.json
glass/base and glass/domainproperties updated to latest versions
> UX Domain Designer: update packages in experiment package.json

- api/webapp/clientapi/ext3/Utils.js
> 38058: showMoveFolderTree.view page has javascript errors

- query/src/org/labkey/query/LinkedTableInfo.java
Per your feedback here: https://github.com/LabKey/platform/commit/cc0446c31bfe33536e9e3bed614fcc7aed9cf696#commitcomment-34222917
> Code review feedback - check if map contains the key instead of value

- api/src/org/labkey/api/dataiterator/TableInsertDataIterator.java
- api/src/org/labkey/api/query/AbstractQueryUpdateService.java
- api/src/org/labkey/api/query/QueryUpdateService.java
- core/src/org/labkey/core/CoreModule.java
- study/src/org/labkey/study/query/DatasetUpdateService.java
InsertOption cleanup, find usages of "option == InsertOption.ENUM"
new property to distinguish "insert or update" and "insert or replace"
> Cleanup InsertOption usages

- internal/webapp/internal/FileDrop/FileDrop.js
- internal/webapp/internal/ZipLoad/ZipLoad.js
Issue 38224: Client side zipping not happening in Microsoft Edge browser
Issue 38225: Relative path in extracted raw data directory not the same as source for client-side zipped directories
Issue 38226: Cannot extract client-side zipped raw data directories on Windows
> Issues: 38224, 38225 and 38226 -Client side zipping issues

- announcements/src/org/labkey/announcements/announcementThread.jsp
- announcements/src/org/labkey/announcements/announcementWebPartWithExpandos.jsp
- announcements/src/org/labkey/announcements/model/AnnouncementDigestProvider.java
- announcements/src/org/labkey/announcements/model/AnnouncementManager.java
- announcements/src/org/labkey/announcements/model/AnnouncementModel.java
- api/src/org/labkey/api/query/UserIdRenderer.java
- api/src/org/labkey/api/security/UserManager.java
- issues/src/org/labkey/issue/view/detailView.jsp
- wiki/src/org/labkey/wiki/WikiController.java
- wiki/src/org/labkey/wiki/model/WikiVersionsGrid.java
Link added to
- Message board: CreatedBy names in thread view.
- Message board: CreatedBy names in responses.
- Issues list: name portion of Open, Changed, Resolved, and Closed fields.
- Wiki: CreatedBy in the wiki history grid.
Method to create the HTML for a link was moved to the UserManager class and they're all referenced from there.
> Issue 6080 (cont.)

- .gitattributes
- devtools/src/org/labkey/devtools/ActionListView.java
- devtools/src/org/labkey/devtools/DevtoolsModule.java
- devtools/src/org/labkey/devtools/TestController.java
- devtools/src/org/labkey/devtools/ToolsController.java
Clean up platform .gitattributes file a bit
> DevTools: Add ToolsController, BeginAction, and GitAttributesAction

- study/src/org/labkey/study/controllers/StudyController.java
- study/src/org/labkey/study/view/viewPreferences.jsp
Manual testing verified that this is working as expected and not causing CSRF errors. Let me know if the code I changed could be further modularized out / repeated code cleaned up.
> 5403: Mutating Operations Warnings, Penultimate 

- api/src/org/labkey/api/action/BaseApiAction.java
- api/src/org/labkey/api/data/ConditionalFormat.java
- api/src/org/labkey/api/data/ResultSetImpl.java
- api/src/org/labkey/api/jsp/taglib/AutoCompleteTag.java
- api/src/org/labkey/api/study/query/PublishResultsQueryView.java
- experiment/src/org/labkey/experiment/api/SampleSetUpdateServiceDI.java
- experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
- internal/webapp/internal/ZipLoad/ZipLoad.js
- pipeline/src/org/labkey/pipeline/PipelineController.java
- study/src/org/labkey/study/assay/PublishConfirmAction.java
@labkey-klum @labkey-adam Please verify my conflict resolution to `PublishConfirmAction.java`
> Merge 19.2.3 to develop

- study/src/org/labkey/study/specimen/report/specimentype/TypeCohortReportFactory.java
Should fix CohortTest failure introduced by (#343)
> Set name of hidden input on cohort form

- api/build.gradle
- search/src/org/labkey/search/model/LuceneSearchServiceImpl.java
- Added dependency for XZ and a test .7z file to sampledata (r64387)
> Issue 38298: Errors when indexing .7z files in search

- api/src/org/labkey/api/query/QuerySettings.java
- api/src/org/labkey/api/reports/ReportService.java
- api/src/org/labkey/api/reports/report/AbstractReportIdentifier.java
- api/src/org/labkey/api/reports/report/DbReportIdentifier.java
- api/src/org/labkey/api/reports/report/RReport.java
- api/src/org/labkey/api/reports/report/ReportDescriptor.java
- api/src/org/labkey/api/reports/report/ReportIdentifierConverter.java
- api/src/org/labkey/api/reports/report/view/ReportUtil.java
- query/src/org/labkey/query/reports/ReportServiceImpl.java
- query/src/org/labkey/query/reports/ReportsController.java
- query/src/org/labkey/query/reports/ReportsWebPartFactory.java
- study/src/org/labkey/study/controllers/StudyController.java
- study/src/org/labkey/study/controllers/reports/ReportsController.java
- study/src/org/labkey/study/view/participantAll.jsp
- study/src/org/labkey/study/view/viewPreferences.jsp
- visualization/src/org/labkey/visualization/VisualizationController.java
Separate PR with minimal test coverage coming in testAutomation repo
> Issue 38403: Support DB report name as URL parameter in addition to RowId

- assay/package-lock.json
- assay/package.json
- experiment/package-lock.json
- experiment/package.json
- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- experiment/src/org/labkey/experiment/createSampleSet.jsp
glass-components PR: https://github.com/LabKey/glass-components/pull/54
Changes to ExperimentController to support the story
> Item #5692: Add import parent alias components for SampleSets

- api/src/org/labkey/api/module/TomcatVersion.java
approved mirror pr: https://github.com/LabKey/platform/pull/333
> Item 5767: Secure ODBC connections

- api/src/org/labkey/api/module/ModuleHtmlView.java
- api/src/org/labkey/api/util/DOM.java
- api/src/org/labkey/api/view/HtmlView.java
- core/src/org/labkey/core/view/template/bootstrap/header.jsp
- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- study/src/org/labkey/study/SpecimenManager.java
- study/src/org/labkey/study/controllers/StudyController.java
I'm not happy with ModuleHtmlView but didn't see an easy way to have access to a fully populated ViewContext where I need it
> Update HtmlView to HtmlString instead of String

- api/webapp/clientapi/dom/DataRegion.js
> Filter out undefined button bar items earlier to avoid needing checks in multiple places.

- api/src/org/labkey/api/assay/actions/newUploadWarnings.jsp
- api/src/org/labkey/api/data/ActionButton.java
- api/src/org/labkey/api/data/DataRegion.java
- api/src/org/labkey/api/data/UrlColumn.java
- api/src/org/labkey/api/jsp/taglib/ButtonTag.java
- api/src/org/labkey/api/reports/report/view/redirectReportWebPart.jsp
- api/src/org/labkey/api/util/Button.java
- api/src/org/labkey/api/util/DOM.java
- api/src/org/labkey/api/util/DisplayElementBuilder.java
- api/src/org/labkey/api/util/HelpTopic.java
- api/src/org/labkey/api/util/Link.java
- api/src/org/labkey/api/view/NavTree.java
- assay/api-src/org/labkey/api/assay/dilution/query/DilutionResultsQueryView.java
- assay/api-src/org/labkey/api/assay/query/RunListDetailsQueryView.java
- core/src/org/labkey/core/admin/customizeEmail.jsp
- core/src/org/labkey/core/admin/moveFolder.jsp
- core/src/org/labkey/core/admin/sql/SqlScriptController.java
- core/src/org/labkey/core/login/resetPassword.jsp
- core/src/org/labkey/core/login/setPassword.jsp
- devtools/src/org/labkey/devtools/TestController.java
- issues/src/org/labkey/issue/view/updateView.jsp
- query/src/org/labkey/query/reports/view/reportDetails.jsp
- study/src/org/labkey/study/designer/view/StudyDesignsWebPart.java
- wiki/src/org/labkey/wiki/view/wikiManage.jsp
> Fb jsp warnings common attr

- study/src/org/labkey/study/StudyServiceImpl.java
- study/src/org/labkey/study/query/VisitTable.java
We should test all the lookup with special handling in StudyServiceImpl.createUnionTable(), but fixing the Visit column will address the current reported problem.
> 19.2 fb 38352 specimen visit lookup

- assay/package-lock.json
- assay/package.json
- experiment/package-lock.json
- experiment/package.json
- with fix for PreviewGrid rendering of integer fields as doubles
> Issue 38127: Update to latest glass release versions

- query/src/org/labkey/query/sql/QueryTableInfo.java
38548: ForeignKeys defined in query metadata.xml do not pick up correct container filter
> 38548: ForeignKeys defined in query metadata.xml do not pick up correct container filter

- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
https://github.com/LabKey/glass-components/pull/67
> Issue 38483: SM app sample set parent import aliases do not execute validation checks

- api/src/org/labkey/api/jsp/taglib/ButtonTag.java
Fix crawler failures with malformed returnUrl
> Null check

- study/src/org/labkey/study/model/DatasetDefinition.java
with per dataset permissions and one with edit all permissions
> Issue 38596: Dataset permissions not additive if user in two groups

- announcements/src/org/labkey/announcements/model/AnnouncementDigestProvider.java
Change from getContainer() to ann.lookupContainer()
> Issue 38629: Changed from get container

- api/src/org/labkey/api/data/Sort.java
38579: NullPointerException with dangling "-" in query.sort parameter
> NPE in parsing badly formed sort parameter

- api/src/org/labkey/api/data/DataColumn.java
- api/src/org/labkey/api/data/RemapCache.java
- api/src/org/labkey/api/data/TableViewForm.java
- core/src/org/labkey/core/CoreModule.java
- experiment/src/org/labkey/experiment/api/ExpRunTableImpl.java
introduce experimental feature to resolve lookups by value (versus key)
> 38504 : Update Run properties fails to resolve string lookups

- api/src/org/labkey/api/data/AbstractForeignKey.java
- api/src/org/labkey/api/data/AbstractTableInfo.java
- api/src/org/labkey/api/data/BaseColumnInfo.java
- api/src/org/labkey/api/data/SchemaTableInfo.java
- api/src/org/labkey/api/data/TableInfo.java
- api/src/org/labkey/api/query/MetadataParseException.java
- api/src/org/labkey/api/query/TableSorter.java
- api/webapp/clientapi/core/Experiment.js
- api/webapp/clientapi/core/Filter.js
- api/webapp/clientapi/dom/DataRegion.js
- core/src/org/labkey/core/view/template/bootstrap/wizard.jsp
- experiment/src/org/labkey/experiment/XarExporter.java
- experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
- query/src/org/labkey/query/ModuleQueryDef.java
- query/src/org/labkey/query/ModuleQueryMetadataDef.java
- query/src/org/labkey/query/QueryDefinitionImpl.java
- query/src/org/labkey/query/QueryImporter.java
- query/src/org/labkey/query/QueryServiceImpl.java
- query/src/org/labkey/query/QueryWriter.java
- query/src/org/labkey/query/controllers/QueryController.java
- query/src/org/labkey/query/persist/QueryDefCache.java
- query/src/org/labkey/query/persist/QueryManager.java
Issue 35668: query metadata xml not exported with folder export 
- export and import metadata xml for built-in tables
Issue 31727: Assays fall back to original file data during export/import
- generate unique path for exp.data created by importRun without real file
> Issue 35668: query metadata xml not exported with folder export

- query/src/org/labkey/query/QueryServiceImpl.java
- case-insensitive match to table name
> Issue 38654: studyData.query.xml not found

- pipeline/src/org/labkey/pipeline/api/PipelineJobServiceImpl.java
Trivial change to avoid failing test.
> 6373: Script-based filewatcher automated tests

- announcements/src/org/labkey/announcements/AnnouncementsController.java
Running green on TC, including DailyC which includes the announcements tests.
> Issue 33909: Standardize Messages Lists webpart dropdown with Messages webpart

- api/src/org/labkey/api/assay/AssayProtocolSchema.java
- api/src/org/labkey/api/exp/api/ExpLineage.java
- api/src/org/labkey/api/exp/api/ExpLineageItem.java
- api/src/org/labkey/api/exp/api/ExpLineageOptions.java
- api/src/org/labkey/api/exp/api/ExpRun.java
- api/src/org/labkey/api/exp/api/ExpRunItem.java
- api/src/org/labkey/api/exp/api/ExperimentService.java
- api/webapp/clientapi/core/Experiment.js
- experiment/src/org/labkey/experiment/api/ExpSampleSetTestCase.java
- experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- support multiple seeds
- support run seeds
- include schemaName/queryName for assay runs in JSON response
> Lineage API: Support multiple seeds and run seeds

- api/src/org/labkey/api/util/DateUtil.java
* Issue 38649: flow: parse fractional seconds used in $BTIM keyword
- parse fractional seconds as milliseconds in DateUtil.parseDateTimeEN()
> Issue 38649: flow: parse fractional seconds used in $BTIM keyword (#501)

- api/src/org/labkey/api/dataiterator/DataIteratorUtil.java
- api/src/org/labkey/api/util/URIUtil.java
> Fix for StudyContinuousTest.testSteps and StudyDateBasedTest.testSteps

- api/src/org/labkey/api/data/DbScope.java
- api/src/org/labkey/api/data/ExcelWriter.java
- assay/src/org/labkey/assay/actions/TemplateAction.java
- core/src/org/labkey/core/security/SecurityController.java
- pipeline/src/org/labkey/pipeline/api/PipelineStatusManager.java
- study/src/org/labkey/study/controllers/StudyController.java
- study/src/org/labkey/study/reports/ExportExcelReport.java
- Eliminate some unused constructors
- Close more ExcelWriters
- Close existing Results before overwriting in setResults(), to handle closing in multi-sheet export case (CDS, ExportExcelReport)
> Close ExcelWriter

- issues/src/org/labkey/issue/view/IssuesWebPartFactory.java
> Issue 38702: Unable to use Issue List web part in container with multiple issue lists defined

- api/webapp/clientapi/core/Domain.js
Hi Kevin! Sorry it took me a little bit to get around to this one.
Here's a pic of the generated docs: 
I looked around but was uncertain if there were any other properties on indices that are supported on the JS API. 
Let me know if you have any feedback! :)
> Issue 38121: JS API documentation for indices on DomainDesign

- api/src/org/labkey/api/data/NameGenerator.java
- api/src/org/labkey/api/exp/SamplePropertyHelper.java
- assay/api-src/org/labkey/api/assay/plate/PlateSamplePropertyHelper.java
- experiment/src/org/labkey/experiment/DerivedSamplePropertyHelper.java
- experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
- experiment/src/org/labkey/experiment/deriveSamplesChooseTarget.jsp
- experiment/src/org/labkey/experiment/summarizeMaterialInputs.jsp
- reuse NameGenerator state between calls to gen derived sample names
> Issue 38204: Name expression not applied when deriving samples

- api/src/org/labkey/api/audit/provider/GroupAuditProvider.java
- core/src/org/labkey/core/user/UserController.java
use the default table view for user details view
> add container column to userAccess.view(s)

- experiment/src/org/labkey/experiment/api/LineageTableInfo.java
Checking in a fix Matt did on my machine. Fix assert with unlocked runs table. Locking the runs table.
> Fix assert with unlocked runs table.

- list/src/org/labkey/list/model/ListImportContext.java
- list/src/org/labkey/list/model/ListImporter.java
- list/src/org/labkey/list/pipeline/ListReloadTask.java
- pipeline/src/org/labkey/pipeline/createPipelineTrigger.jsp
- study/src/org/labkey/study/controllers/StudyController.java
- study/src/org/labkey/study/importer/DatasetDefinitionImporter.java
- study/src/org/labkey/study/importer/StudyImportContext.java
- study/src/org/labkey/study/model/StudyManager.java
- study/src/org/labkey/study/pipeline/FileAnalysisDatasetTask.java
test automation for lists and datasets
> 6465 : add support for list and dataset filewatchers to prevent domain updates

- api/src/org/labkey/api/data/StatementUtils.java
- Include dialect when calling AliasManager to handle reserved words
> Issue 38291: merge fails with "group" column

- experiment/resources/schemas/dbscripts/postgresql/exp-19.20-19.21.sql
38835 fix performance of exp-19.20-19.21
> replace "NOT IN" with "LOJ WHERE...IS NULL"

- internal/webapp/vis/src/internal/D3Renderer.js
- causing BiologicsAssayTest.validateAssayRunChartsFilters failure
> Issue 38848: D3Renderer fix for legend text JS error

- api/src/org/labkey/api/data/CompareType.java
teach ~q filter to include PK column if search term is an integer
> Issue 38712: cannot search for issue number in assay request field

- api/src/org/labkey/api/query/TableSorter.java
- ignore schemas that can't be sorted if all tables have no container column
> Issue 37270: container delete fails for unsortable schema

- assay/package-lock.json
- assay/package.json
- experiment/package-lock.json
- experiment/package.json
Some classes were factored out of domainproperties into base to make the names more general for use in other places.
> Story 6265: Update package versions for CSS class renames

- api/src/org/labkey/api/query/QueryView.java
- include details and edit URL when includeDetailsColumn or includeUpdateColumn is true
> Issue 37776: updateUrl in custom assay does not get used in Biologics UI

- core/src/org/labkey/core/login/LoginController.java
Also use standard naming pattern for action
> Issue 38918: Fix LoginController$TestCase failure

- query/src/org/labkey/query/LinkedSchema.java
- query/src/org/labkey/query/LinkedSchemaQueryDefinition.java
…ma results in UnsupportedOperationException
> Issue 38903: QueryWebPart setting metadata xml on table in LinkedSchema results in UnsupportedOperationException

- mothership/src/org/labkey/mothership/query/MothershipSchema.java
Fix SQL expression for SQL Server
> Issue 38803: Update VCS info reporting to mothership

- experiment/test/src/org/labkey/test/tests/experiment/VocabularyViewSupportTest.java
No need to click "Finish" after creating a sample set
> Update vocabulary test for UI change

- assay/package-lock.json
- assay/package.json
- experiment/package-lock.json
- experiment/package.json
- experiment/src/client/DomainDesigner/DomainDesigner.tsx
- Only disable single domain save button when submitting.  No longer disabled when errors exist.
- Update to latest versions of domainproperties
> Item 6528: Update domainproperties version and Domain Designer

- filecontent/src/org/labkey/filecontent/FileContentController.java
Small benefit for SNPRC FWP scenario, but not a significant improvement
> Filter out null dataFileURLs in the DB query instead of Java for small perf win

- internal/webapp/extWidgets/IconPanel.css
https://www.labkey.org/issues/home/Developer/issues/details.view?issueId=38996
> Issue 38996: Fix project webpart outline around file icon when clicked/focus

- api/src/org/labkey/api/jsp/JspClassLoader.java
- use getExplodedDir() insteadof getModuleResource()
- partial fix for 39046: RecompilingJspClassLoader cannot handle "/java" prefix used in Biologics
> JspClassLoader fix for dev mode

- issues/src/org/labkey/issue/IssueUpdateEmailTemplate.java
- issues/src/org/labkey/issue/actions/ChangeSummary.java
- issues/src/org/labkey/issue/model/Issue.java
- issues/src/org/labkey/issue/view/detailView.jsp
- issues/src/org/labkey/issue/view/rss.jsp
remove getters for optional fields so we don't create a bean from the form with fields that may not actually exist in the post
> 38993 : BatchValidationException updating an issue in client portal

- api/build.gradle
- api/resources/credits/remoteapi_jars.txt
- api/src/org/labkey/api/ApiModule.java
- api/src/org/labkey/api/jsp/RecompilingJspClassLoader.java
- core/resources/credits/jars.txt
- core/src/org/labkey/core/CoreModule.java
- core/src/org/labkey/core/admin/AdminController.java
Copy remoteapi jars into api/lib. Remove product references to WEB-INF/lib.
> Issue 38600: Move remoteapi jars to standard location

- api/src/org/labkey/api/assay/AbstractAssayTsvDataHandler.java
- api/src/org/labkey/api/data/RemapCache.java
Fix LookupToSampleIdTest.testSamplesSameContainerIntegerWarning
> RemapCache should use provided lookup table when translating values

- experiment/resources/schemas/dbscripts/postgresql/exp-19.31-19.32.sql
- experiment/resources/schemas/dbscripts/sqlserver/exp-19.31-19.32.sql
- experiment/src/org/labkey/experiment/ExperimentModule.java
> Item 6510: Sample Manager Workflow - Support larger comment threads

- api/src/org/labkey/api/security/AuthenticationManager.java
- api/src/org/labkey/api/settings/LookAndFeelPropertiesManager.java
- api/src/org/labkey/api/util/PageFlowUtil.java
- api/src/org/labkey/api/view/template/PageConfig.java
- assay/package-lock.json
- assay/package.json
- core/resources/themes/sky/_variables.scss
- core/resources/views/login.html
- core/resources/views/register.html
- core/src/org/labkey/core/CoreModule.java
- core/src/org/labkey/core/admin/AdminController.java
- core/src/org/labkey/core/admin/lookAndFeelProperties.jsp
- core/src/org/labkey/core/login/LoginController.java
- core/src/org/labkey/core/login/finishResetPassword.jsp
- core/src/org/labkey/core/login/resetPassword.jsp
- core/src/org/labkey/core/login/setPassword.jsp
- core/src/org/labkey/core/security/SecurityApiActions.java
- core/src/org/labkey/core/view/template/bootstrap/header.jsp
- core/webapp/login.css
- core/webapp/register.js
- devtools/src/org/labkey/devtools/authentication/TestSecondaryController.java
- experiment/package-lock.json
- experiment/package.json
- wiki/src/org/labkey/wiki/WikiModule.java
- removes new user first login auto redirect to profile page
- consolidate login page and password related pages (reset, set, upset) styling and page layout
- factor out LookAndFeelPropertiesManager to use for setting site logo, icon, and custom stylesheet during startup properties
- add support for startup property to set the home project folder type
- new theme: Sky, similar to overcast but uses the SM app primary and secondary colors
> Item 5511: Changes to better support login and password actions for SM app

- experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
- Add 'Type' to search terms
https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=39257
> SM Type keyword nets 0 results, should include Sample Types 

- experiment/src/org/labkey/experiment/LSIDRelativizer.java
Fix test failures related to AutoFileLSIDs
Example: https://teamcity.labkey.org/viewLog.html?buildId=876951&tab=buildResultsDiv&buildTypeId=LabKey_Trunk_LabkeyPremiumTrunk_GitModules_NlpPostgres95#testNameId-7670985145100695067
https://teamcity.labkey.org/repository/download/LabKey_Trunk_LabkeyPremiumTrunk_GitModules_NlpPostgres95/876951:id/NLPCoreTest.tar.gz!/NLPCoreTestProject/%40files/Permissive_2019-12-21_06-03-08/nlpEngineInvocation/Permissive/sample1.log
> Issue 39260: Perf problem in org.labkey.experiment.LSIDRelativizer$RelativizedLSIDs.relativize()

- assay/package-lock.json
- assay/package.json
- experiment/package-lock.json
- experiment/package.json
- experiment/src/client/DomainDesigner/DomainDesigner.tsx
- experiment/src/client/DomainDesigner/domainDesigner.scss
- Fix for button spacing and layout on single domain designer page
>  Misc domain designer fixes for Sample Manager

- api/src/org/labkey/api/assay/AssayService.java
- api/src/org/labkey/api/exp/api/ExpProtocol.java
- assay/src/org/labkey/assay/AssayManager.java
- experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
Prior, a new assay is not indexed until the next time the container is indexed. Similarly, after deletion the assay is not removed. This should make that more responsive.
Result of trying to fix: https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=39171
Related PRs:
https://github.com/LabKey/sampleManagement/pull/129
https://github.com/LabKey/labkey-ui-components/pull/126
> Assays aren't indexed or unindexed in a short enough period

- experiment/src/org/labkey/experiment/api/ExpProtocolApplicationTableImpl.java
resolve to exp.materials sample schema if the column has not already been resolved elsewhere.
> Issue 39301: Add resolveColumn method that will resolve a Material column 

- assay/api-src/org/labkey/api/assay/AssayResultTable.java
(aside from the perf issue) there are many column in exp.Data we are not exposing such as modified, which I believe I've heard requested.
> don't double join to exp.Data

- api/src/org/labkey/api/data/CompareType.java
Convert to doubles when comparing conditional format filter value against a different numeric value type
> Issue 39395: ClassCastException rendering conditional formats

- assay/package-lock.json
- assay/package.json
- assay/src/client/AssayDataImport/AssayDataImport.tsx
- core/package-lock.json
- experiment/package-lock.json
- experiment/package.json
https://github.com/LabKey/labkey-ui-components/pull/132
https://github.com/LabKey/sampleManagement/pull/142
> Omit some property types from the field designer for SM

- api/src/org/labkey/api/util/DateUtil.java
- turn off strict overflow checking for jiffy seconds > 59 for bad flow data
> Issue 38649: flow: parse fractional seconds used in $BTIM keyword
